In [66]:
# coding:utf8
import numpy as np
import pandas as pd

In [67]:
'''
结合 numpy 创建一个 (3, 10) 区间内的包含 5 个随机整数的一维数组 ndarray 为 data1，
并以此 data 再创建索引为 a, b, c, d, e 的 Series 为 s1（任务提示：利用 np.random.randint() 创建随机矩阵。阅读参考文章①②）
https://blog.csdn.net/zsc201825/article/details/80918450
https://www.jianshu.com/p/e318c1301fa8
'''

# Series 数据结构
# Series 是带有标签的一维数组，可以保存任何数据类型（整数，字符串，浮点数，Python对象等）,轴标签统称为索引

# y1=np.random.randint(2,10,(3,2)) 解释：生成3行2列的数组，取值范围[2,10)之间

# a1=np.array([3,5,2.6,41.2,5.7])
# a2 = np.random.choice(a=a1, size=3, replace=False, p=[0.2, 0.1, 0.3, 0.4, 0.0])
# 解释：1、以p的概率，在a中取size个数，p值越大越可能被取到；2、当replace=True时，取值可重复

# y=list(range(1,10))
# slice = random.sample(y, 5) 
# 解释：从list中随机获取5个元素，作为一个列表
# 注意：此random.sample，不是np.random.sample，算法使用不同

# 创建方法：
# Series 创建方法一：由字典创建，字典的key就是index，values就是values
# dic = {'a':1 ,'b':2 , 'c':3, '4':4, '5':5}
# Series 创建方法二：由数组创建(一维数组)
# arr = np.random.randn(5)
# s = pd.Series(arr)
# s = pd.Series(arr, index = ['a','b','c','d','e'],dtype = np.object)
# index参数：设置index，长度保持一致。不设置时默认index是从0开始，步长为1的数字
# dtype参数：设置数值类型

# Series 创建方法三：由标量创建
# s = pd.Series(10, index = range(4)) 如果data是标量值，则必须提供索引。该值会重复，来匹配索引的长度

# Series 名称属性：name
# s1 = pd.Series(np.random.randn(5))
# s2 = pd.Series(np.random.randn(5),name = 'test')
# s3 = s2.rename('hehehe')

data1 = np.random.randint(3,10,5)
s1 = pd.Series(data1,index=['a','b','c','d','e'])
s1

a    6
b    7
c    8
d    4
e    5
dtype: int64

In [68]:
'''
请分别用位置索引和标签索引的方式提取是 s1 的后三个数（阅读参考文章③）
https://blog.csdn.net/weixin_42652294/article/details/82772325
'''

a = s1[-3:]
b = s1['c':'e']
# c = s1['c':]

In [79]:
'''
请用字典的形式创建一个DataFrame，将下方表格数据存储进去 （任务提示：创建 DataFrame 有多种方式，本题以字典形式创建。阅读参考文章④）
https://zhuanlan.zhihu.com/p/37856914
'''
# 1) 由数组列表组成的字典
# data1 = {'four':np.arange(4,9), 'one':range(1,6), 'three':[3,4,5,6,7],'two':range(2,7)}
# print(pd.DataFrame(data1, index=list('abcde')))

# 2) 由Series组成的字典
# data2 = {'four':pd.Series(np.arange(4,9), index=list('abcde')), 
#          'one':pd.Series(range(1,6), index=list('abcde')),
#          'three':pd.Series((3,4,5,6,7), index=list('abcde')),
#          'two':pd.Series(range(2,7), index=list('abcde'))}
# print(pd.DataFrame(data2))

# 3) 通过二维数组直接创建
# data3=np.array([4,1,3,2,5,2,4,3,6,3,5,4,7,4,6,5,8,5,7,6]).reshape(5,4)
# print(pd.DataFrame(data3, index=list('abcde'), columns=['four', 'one', 'three', 'two']))

# 4) 由字典组成的列表
# data4 = [{'four':4,'one':1,'three':3,'two':2}, {'four':5,'one':2,'three':4,'two':3},
#          {'four':6,'one':3,'three':5,'two':4}, {'four':7,'one':4,'three':6,'two':5}, 
#         {'four':8,'one':5,'three':7,'two':6}]
# print(pd.DataFrame(data4, index=list('abcde')))

# 5) 由字典组成的字典
# data5 = {'four':{'a':4, 'b':5, 'c':6, 'd':7, 'e':8}, 
#         'one':{'a':1, 'b':2, 'c':3, 'd':4, 'e':5}, 
#         'three':{'a':3, 'b':4, 'c':5, 'd':6, 'e':7}, 
#         'two':{'a':2, 'b':3, 'c':4, 'd':5, 'e':6}}
# print(pd.DataFrame(data5, index=list('abcde'), columns=['four', 'one', 'three','two']))

data_dict = {'year':[2017,2018,2019],'price':[10,20,30]}
datas = pd.DataFrame(data_dict)
datas

   year  price
0  2017     10
1  2018     20
2  2019     30

In [70]:
'''
结合 numpy 创建一个 (5, 15) 区间内，形状为 5 行 3 列的随机整数数组为 data2，并以此为基础创建 index 为 ['a', 'c', 'e', 'f', 'h']，
columns 为 ['one', 'two', 'three'] 的 DataFrame，并命名为 df_test（阅读参考文章④）
'''

data2 = np.random.randint(5,15,15).reshape(5,3)
df_test = pd.DataFrame(data2,index = ['a', 'c', 'e', 'f', 'h'],columns = ['one', 'two', 'three'])
df_test

   one  two  three
a    6    7      8
c   10    7      6
e    8   11     12
f   13    7     11
h   14   13     12

In [75]:
'''
运用 loc 索引以及替换的知识，按下列要求对 df_test 进行增、改、替操作。
完成上述要求后，将该数据命名为 df_change（任务提示：一般用 df.loc[行，列] = ？ 做替换。阅读参考文章⑤⑥）
(1) 将 a 行 one 列处替换成空值;(2) 将 c 行 two 列处替换成 -99;(3) 将 c 行 three 列处替换成 -99;(4) 将 a 行 two 列处替换成 -100;
(5) 新增 four 列，值为 test;(6) 重置索引为 ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
https://blog.csdn.net/The_Time_Runner/article/details/84075409
https://blog.csdn.net/youngbit007/article/details/53067707
'''

# DataFrame如何对某行某列的单个元素进行替换(loc[]、iloc[]、at[]区别)
# 在DataFrame文件中，对i行j列的那个元素进行替换、插入数据操作，采用的是pd.loc[]
# pd.iloc[i,j] i,j 只能是数字，即原始索引。
# pd.loc[i,‘j’] i,j既可以是数字，也可是字母，即索引标签；更适用于一段数据。
# pd.at[i,‘j’] i,j既可以是数字，也可是字母，不同的是，当定位的是某个具体的元素时，用at[]效率更高。
# 这两个函数经常用来提取指定位置的数据，直接对其赋值也是可以的。
# pd.loc[i,j] = value

# pandas的reindex对象，是数据符合新的索引来构造一个新的对象
# Series的reindex使它符合新的索引，如果索引的值不存在就填入缺失值

# method选项来控制填充值或内插值：
# method : {None, ‘backfill’/’bfill’, ‘pad’/’ffill’, ‘nearest’}, optional。
# ffill/pad 向前或进位填充，bfill/backfill 向后或补位填充

# (1) 将 a 行 one 列处替换成空值
df_test.loc['a','one'] = ''

# df_test.loc['c','two':'three']=-99
# (2) 将 c 行 two 列处替换成 -99
df_test.loc['c','two'] = -99
# (3) 将 c 行 three 列处替换成 -99
df_test.loc['c','three'] = -99

# (4) 将 a 行 two 列处替换成 -100
df_test.loc['a','two'] = -100

# (5) 新增 four 列，值为 test
df_test.loc[:,'four'] = 'test'

# (6) 重置索引为 ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
df_change = df_test.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [86]:
'''
删除 df_change 中存在缺失值的所有行
删除 df_change 中所有值都为 NaN 值的行
df_change 中的所有缺失值（即 NaN）以 0 填充（阅读参考文章⑦）
https://blog.csdn.net/duxu24/article/details/75058538
'''

# df.isnull()#是缺失值返回True，否则范围False
# df.isnull().sum()#返回每列包含的缺失值的个数
# df.dropna()#直接删除含有缺失值的行
# df.dropna(axis = 1)#直接删除含有缺失值的列
# df.dropna(how = 'all')#只删除全是缺失值的行
# df.dropna(thresh = 4)#保留至少有4个缺失值的行
# df.dropna(subset = ['C'])#删除含有缺失值的特定的列

# df.fillna(0)：用0填充 df.fillna('a')
# df.fillna(method='pad')：用前一个数值填充
# df.fillna(df2.mean())：用该列均值填充

df_contain_nan = df_change.dropna()
df_row_nan = df_change.dropna(how = 'all')
df_fill_nan = df_change.fillna(0)

In [89]:
'''
删除 df_change中的重复行（阅读参考文章⑧）
https://blog.csdn.net/erinapple/article/details/79332780
'''

# newDF = df.drop_duplicates()

df_del_samerow = df_change.drop_duplicates()
df_del_samerow

   one    two  three  four
a      -100.0    8.0  test
b  NaN    NaN    NaN   NaN
c   10  -99.0  -99.0  test
e    8   11.0   12.0  test
f   13    7.0   11.0  test
h   14   13.0   12.0  test